# Form implementation generated from reading ui file 'D:\GIT\ddyun\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from titleBar import TitleBar, MainWindow
import icon_rc
from qiniuS3 import QiniuS3
import conf

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 546)
        self.manWindow = MainWindow

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 751, 531))
        self.frame.setMinimumSize(QtCore.QSize(751, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = MainWindow.title_bar
        self.frame_2.setParent(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius: 16px;\n"
"border-top-left-radius: 16px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")


        

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    padding-left: 10px;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/yun.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_5.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    padding-bottom: 5px;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_6.setFont(font)
        self.frame_6.setStyleSheet("#frame_6 { \n"
"    background-color: rgb(76, 76, 76);\n"
"    border-bottom-left-radius: 16px;\n"
"    padding-bottom: 15px;\n"
"    padding-top: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    color: rgb(203, 203, 203);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_synchronize = QtWidgets.QPushButton(parent=self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_synchronize.setFont(font)
        self.pushButton_synchronize.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_synchronize.setObjectName("pushButton_synchronize")
        self.verticalLayout_2.addWidget(self.pushButton_synchronize)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButton_config = QtWidgets.QPushButton(parent=self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_config.setFont(font)
        self.pushButton_config.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_config.setObjectName("pushButton_config")
        self.verticalLayout_2.addWidget(self.pushButton_config)
        self.pushButton_ablout = QtWidgets.QPushButton(parent=self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ablout.setFont(font)
        self.pushButton_ablout.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_ablout.setObjectName("pushButton_ablout")
        self.verticalLayout_2.addWidget(self.pushButton_ablout)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-right-radius: 16px;\n"
"}\n"
"QLineEdit,QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_7)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 601, 491))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_8 = QtWidgets.QFrame(parent=self.page)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 601, 491))
        self.frame_8.setMinimumSize(QtCore.QSize(600, 490))
        self.frame_8.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    color: rgb(90, 90, 90);\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.pushButton_uploadDir= QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_uploadDir.setGeometry(QtCore.QRect(180, 110, 220, 80))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton_uploadDir.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/cloud-upload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_uploadDir.setIcon(icon3)
        self.pushButton_uploadDir.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_uploadDir.setObjectName("pushButton_uploadDir")
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.pushButton_downloadDir = QtWidgets.QPushButton(parent=self.frame_10)
        self.pushButton_downloadDir.setGeometry(QtCore.QRect(180, 80, 220, 80))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton_downloadDir.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/cloud-download.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_downloadDir.setIcon(icon4)
        self.pushButton_downloadDir.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_downloadDir.setObjectName("pushButton_downloadDir")
        self.verticalLayout_3.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_11 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 600, 490))
        self.frame_11.setMinimumSize(QtCore.QSize(600, 490))
        self.frame_11.setStyleSheet("QLineEdit {\n"
"    font: 12pt \"Microsoft YaHei UI\";\n"
"}\n"
"QComboBox {\n"
"    font: 12pt \"Microsoft YaHei UI\";\n"
"}\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.domain = QtWidgets.QLineEdit(parent=self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.domain.setFont(font)
        self.domain.setText("")
        self.domain.setMaxLength(200)
        self.domain.setObjectName("domain")
        self.verticalLayout_4.addWidget(self.domain)
        self.accessKey = QtWidgets.QLineEdit(parent=self.frame_13)
        self.accessKey.setObjectName("accessKey")
        self.verticalLayout_4.addWidget(self.accessKey)
        self.secretKey = QtWidgets.QLineEdit(parent=self.frame_13)
        self.secretKey.setObjectName("secretKey")
        self.verticalLayout_4.addWidget(self.secretKey)
        self.bucket = QtWidgets.QLineEdit(parent=self.frame_13)
        self.bucket.setObjectName("bucket")
        self.verticalLayout_4.addWidget(self.bucket)
        self.local_dir = QtWidgets.QLineEdit(parent=self.frame_13)
        self.local_dir.setObjectName("local_dir")
        self.verticalLayout_4.addWidget(self.local_dir)
        self.timeout = QtWidgets.QLineEdit(parent=self.frame_13)
        self.timeout.setObjectName("timeout")
        self.verticalLayout_4.addWidget(self.timeout)
        self.Addressing = QtWidgets.QComboBox(parent=self.frame_13)
        self.Addressing.setObjectName("Addressing")
        self.Addressing.addItem("")
        self.Addressing.addItem("")
        self.verticalLayout_4.addWidget(self.Addressing)
        self.TLS_Verify = QtWidgets.QComboBox(parent=self.frame_13)
        self.TLS_Verify.setObjectName("TLS_Verify")
        self.TLS_Verify.addItem("")
        self.TLS_Verify.addItem("")
        self.verticalLayout_4.addWidget(self.TLS_Verify)
        self.verticalLayout_5.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("QPushButton {\n"
"    font: 12pt \"Microsoft YaHei UI\";\n"
"    border: 1px solid;\n"
"    border-radius: 5px;\n"
"}\n"
"#frame_12 {\n"
"    padding-right: 5px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_10.setStyleSheet("background-color: rgb(104, 104, 104);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.verticalLayout_5.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_14 = QtWidgets.QFrame(parent=self.page_3)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 601, 491))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label = QtWidgets.QLabel(parent=self.frame_14)
        self.label.setGeometry(QtCore.QRect(110, 200, 221, 101))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_synchronize.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.pushButton_config.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.pushButton_ablout.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))

        self.pushButton_downloadDir.clicked.connect(self.downloadDir)
        self.pushButton_uploadDir.clicked.connect(self.uploadDir)

        self.pushButton_9.clicked.connect(self.updateConfig)
        self.pushButton_10.clicked.connect(self.loadConfig)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " ddyun"))
        self.pushButton_synchronize.setText(_translate("MainWindow", "同步"))
        self.pushButton_config.setText(_translate("MainWindow", "设置"))
        self.pushButton_ablout.setText(_translate("MainWindow", "关于"))
        self.pushButton_uploadDir.setText(_translate("MainWindow", "  上传"))
        self.pushButton_downloadDir.setText(_translate("MainWindow", "  下载"))
        self.domain.setToolTip(_translate("MainWindow", "domain"))
        self.domain.setPlaceholderText(_translate("MainWindow", "domain"))
        self.accessKey.setPlaceholderText(_translate("MainWindow", "Access Key"))
        self.secretKey.setPlaceholderText(_translate("MainWindow", "Secret Key"))
        self.bucket.setPlaceholderText(_translate("MainWindow", "Bucket"))
        self.local_dir.setPlaceholderText(_translate("MainWindow", "local_dir"))
        self.timeout.setPlaceholderText(_translate("MainWindow", "Timeout(s)"))
        self.Addressing.setPlaceholderText(_translate("MainWindow", "Addressing"))
        self.Addressing.setItemText(0, _translate("MainWindow", "Path-style"))
        self.Addressing.setItemText(1, _translate("MainWindow", "virtual-hosted-style"))
        self.TLS_Verify.setPlaceholderText(_translate("MainWindow", "TLS Verify"))
        self.TLS_Verify.setItemText(0, _translate("MainWindow", "verify"))
        self.TLS_Verify.setItemText(1, _translate("MainWindow", "skip"))
        self.pushButton_10.setText(_translate("MainWindow", "取消"))
        self.pushButton_9.setText(_translate("MainWindow", "确定"))
        self.label.setText(_translate("MainWindow", "Version： 0.0.1"))
        self.loadConfig()
    def resizeEvent(self, event):
        self.resize(self.sizeHint())

    def uploadDir(self):
        _translate = QtCore.QCoreApplication.translate
        # self.pushButton.setText(_translate("MainWindow", " ddyun  开始上传，请稍等..."))
        qiniu_s3 = QiniuS3()
        qiniu_s3.upload_directory(conf.config['local_dir'])
        self.pushButton.setText(_translate("MainWindow", " ddyun  上传完成"))  # 更新状态消息

    def downloadDir(self):
        _translate = QtCore.QCoreApplication.translate
        # self.pushButton.setText(_translate("MainWindow", " ddyun  开始下载..."))
        qiniu_s3 = QiniuS3()
        qiniu_s3.download_directory(conf.config['local_dir'])
        self.pushButton.setText(_translate("MainWindow", " ddyun  下载完成"))  # 更新状态消息

    def loadConfig(self):
        self.domain.setText(conf.config['domain'])
        self.accessKey.setText(conf.config['access_key'])
        self.secretKey.setText(conf.config['secret_key'])
        self.bucket.setText(conf.config['bucket_name'])
        self.local_dir.setText(conf.config['local_dir'])

    def updateConfig(self):
        conf.config['domain'] = self.domain.text()
        conf.config['access_key'] = self.accessKey.text()
        conf.config['secret_key'] = self.secretKey.text()
        conf.config['bucket_name'] = self.bucket.text()
        conf.config['local_dir'] = self.local_dir.text()
        encrypted_config = conf.encrypt_config(conf.config, conf.key)  
        conf.persist_config(encrypted_config, 'config.pickle')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = MainWindow()
    # mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
